apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    release: {{ .Release.Name }}
  {{- with .Values.deploymentLabels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      {{- toYaml .Values.deploymentSelectorMatchLabels | nindent 6 }}
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
      {{- with .Values.podLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/service-config.yaml") . | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.containerAdminPort }}"
      {{- with .Values.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
    {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: service-config
          configMap:
            name: {{ .Values.hypertraceDataConfigServiceConfig.name }}
        - name: attribute-service-config
          configMap:
            name: {{ .Values.attributeServiceConfig.name }}
        - name: entity-service-config
          configMap:
            name: {{ .Values.entityServiceConfig.name }}
        - name: config-service-config
          configMap:
            name: {{ .Values.configServiceConfig.name }}
        - name: log4j-config
          configMap:
            name: {{ .Values.logConfig.name }}
      {{- with .Values.nodeLabels }}
      nodeSelector:
      {{- toYaml . | nindent 8}}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ include "hypertraceDataConfigService.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc-port
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
            - name: admin-port
              containerPort: {{ .Values.containerAdminPort }}
              protocol: TCP
          env:
            - name: LOG4J_CONFIGURATION_FILE
              value: "/var/{{ .Chart.Name }}/log/log4j2.properties"
            - name: JAVA_OPTS
              value: {{ .Values.javaOpts | quote }}
          volumeMounts:
            - name: service-config
              mountPath: /app/resources/configs/{{ .Values.hypertraceDataConfigServiceConfig.name }}/application.conf
              subPath: application.conf
            - name: attribute-service-config
              mountPath: /app/resources/configs/attribute-service/default-cluster/default-pod/application.conf
              subPath: application.conf
            - name: entity-service-config
              mountPath: /app/resources/configs/entity-service/default-cluster/default-pod/application.conf
              subPath: application.conf
            - name: config-service-config
              mountPath: /app/resources/configs/config-service/default-cluster/default-pod/application.conf
              subPath: application.conf
            - name: log4j-config
              mountPath: /var/{{ .Chart.Name }}/log
          livenessProbe:
            initialDelaySeconds: {{ int .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ int .Values.livenessProbe.periodSeconds }}
            tcpSocket:
              port: grpc-port
          readinessProbe:
            initialDelaySeconds: {{ int .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ int .Values.readinessProbe.periodSeconds }}
            httpGet:
              path: /health
              port: {{ .Values.containerAdminPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}